
(function(){
const DATA=window.PTA_BOARD_RESPONSE_INDEX||{}; const state={filter:'all',query:''};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const typeLabel=k=>DATA.typeMap?.[k]?.label||k;
function renderStats(){const el=document.getElementById('summaryStats'); if(!el)return; const total=DATA.totalMunicipalities||0, details=(DATA.details||[]).length, typeCount=Object.keys(DATA.typeMap||{}).length, multi=(DATA.municipalities||[]).filter(x=>(x.types||[]).length>1).length; el.innerHTML=`<div class="board-stat"><div class="board-stat__num">${total}</div><div class="board-stat__label">自治体索引</div></div><div class="board-stat"><div class="board-stat__num">${details}</div><div class="board-stat__label">回答本文</div></div><div class="board-stat"><div class="board-stat__num">${typeCount}</div><div class="board-stat__label">質問類型</div></div><div class="board-stat"><div class="board-stat__num">${multi}</div><div class="board-stat__label">複数類型</div></div>`}
function renderTypes(){const el=document.getElementById('typeGrid'); if(!el)return; el.innerHTML=Object.entries(DATA.typeMap||{}).filter(([k])=>(DATA.typeCounts?.[k]||0)>0).map(([k,i])=>`<article class="type-card"><div class="type-card__key">${esc(k)}</div><div class="type-card__title">${esc(i.title)}</div><div class="type-card__count">${esc(DATA.typeCounts?.[k]||0)}</div><div class="type-card__desc">${esc(i.short)}</div></article>`).join('')}
function matchM(x){return (state.filter==='all'||(x.types||[]).includes(state.filter))&&(!state.query||[x.municipality,x.no,...(x.types||[]),...Object.values(x.raw||{}),x.firstBody].join(' ').includes(state.query))}
function renderIndex(){const tbody=document.getElementById('indexTableBody'); if(!tbody)return; const items=(DATA.municipalities||[]).filter(matchM); if(!items.length){tbody.innerHTML='<tr><td colspan="9">条件に一致する自治体はありません。</td></tr>';return} tbody.innerHTML=items.map(item=>`<tr><td>${esc(item.no)}</td><td><strong>${esc(item.municipality)}</strong><br><small>${esc(item.detailCount||0)}件の本文</small></td>${['A','B','C','D','E','F','G'].map(k=>`<td>${(item.types||[]).includes(k)?`<span class="type-pill">${esc(typeLabel(k))}</span>`:''}</td>`).join('')}</tr>`).join('')}
function renderDetails(){const grid=document.getElementById('detailGrid'); if(!grid)return; const items=(DATA.details||[]).filter(x=>(state.filter==='all'||x.type===state.filter)&&(!state.query||[x.municipality,x.date,x.typeLabel,x.typeTitle,x.body].join(' ').includes(state.query))); if(!items.length){grid.innerHTML='<div class="card">条件に一致する回答本文はありません。</div>';return} grid.innerHTML=items.map(x=>`<details class="answer-accordion"><summary><span>${esc(x.municipality)}<span class="answer-accordion__meta">${esc(x.date||'日付未入力')}｜${esc(x.typeLabel)}｜${esc(x.typeTitle)}</span></span></summary><div class="answer-accordion__body">${esc(x.body||'本文未入力')}</div></details>`).join('')}
function init(){const params=new URLSearchParams(location.search); const initialType=params.get('type'); const initialQuery=params.get('q'); if(initialType&&DATA.typeMap?.[initialType])state.filter=initialType; if(initialQuery)state.query=initialQuery; document.querySelectorAll('[data-board-filter]').forEach(btn=>{const k=btn.dataset.boardFilter;if(k!=='all'&&(DATA.typeCounts?.[k]||0)===0)btn.style.display='none'; btn.addEventListener('click',()=>{state.filter=btn.dataset.boardFilter;document.querySelectorAll('[data-board-filter]').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');renderIndex();renderDetails()})}); document.querySelectorAll('[data-board-filter]').forEach(b=>b.classList.toggle('is-active',b.dataset.boardFilter===state.filter)); const input=document.getElementById('responseSearch'); if(input){input.value=state.query;input.addEventListener('input',()=>{state.query=input.value.trim();renderIndex();renderDetails()})} renderStats();renderTypes();renderIndex();renderDetails();}
document.addEventListener('DOMContentLoaded',init);
})();
